# Default values for lakehouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

instanceName: lakehouse-a

namespace: pgr24james

trino:
  pod:
    image: 2570809n/trino-node-exporter:latest
  worker:
    resources:
        cpu: "4"
        memory: "64Gi"
    replicasPerNode: 1
    nodes:
      - "idagpu-19"
      - "idagpu-20"
      - "idagpu-21"
      - "idagpu-22"
  coord:
    resources:
      cpu: "4"
      memory: "64Gi"
    nodeName: "idagpu-23"  # or "" to disable

test:
  pod:
    image: macavaney/idabox:py310-v93

metastore:
  nodeName: "idagpu-12"  # or "" to disable
  hive:
    pod:
      image: bde2020/hive:latest
  postgres:
    pod:
      image: postgres:13

pvc:
  iceberg:
    name: iceberg-pvc-a