apiVersion: v1
kind: Pod
metadata:
  name: hive-metastore-postgres-{{ .Values.instanceName }}
  namespace: pgr24james
  labels:
    app: hive-pod-{{ .Values.instanceName }}  # matches the existing service selector
spec:
  {{- if .Values.metastore.nodeName }}
  nodeName: {{ .Values.metastore.nodeName | quote }}
  {{- end }}
  initContainers:
    - name: prefill
      image: macavaney/idabox:py310-v105
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          python /mnt/primary/Mini-project/Apache/System/Queries/TPCDS/Time_Workload/isolated_data/move_datalake.py
      volumeMounts:
        - name: pgr24jamesvol1claim
          mountPath: /mnt/primary
        - name: empty-warehouse
          mountPath: /mnt/empty_warehouse_dir
        - name: {{ .Values.pvc.iceberg.name }}
          mountPath: /mnt/iceberg
      resources:
        requests:
          cpu: "4"
          memory: "20Gi"
        limits:
          cpu: "4"
          memory: "20Gi"
      securityContext:
        capabilities:
          drop: [ "MKNOD" ]
  containers:
    - name: hive-metastore
      image: {{ .Values.metastore.hive.pod.image }}
      env:
        - name: METASTORE_LISTEN_HOST
          value: "0.0.0.0"
        - name: METASTORE_PORT
          value: "9083"
      ports:
        - containerPort: 9083
      command: ["/bin/bash", "-c"]
      args:
          - | 
            schematool -initSchema -dbType postgres && \
            hive --service metastore
      volumeMounts:
        - name: pgr24jamesvol1claim
          mountPath: /mnt/primary/
        - name: hive-site-config-{{ .Values.instanceName }}
          mountPath: /opt/hive/conf
        - name: empty-warehouse
          mountPath: /mnt/iceberg/warehouse
      securityContext:
        capabilities:
          drop:
            - MKNOD
      imagePullPolicy: IfNotPresent

    - name: postgres
      image: {{ .Values.metastore.postgres.pod.image }}
      env:
        - name: POSTGRES_DB
          value: metastore
        - name: POSTGRES_USER
          value: hive
        - name: POSTGRES_PASSWORD
          value: hivepass
      volumeMounts:
        - name: empty-warehouse
          mountPath: /mnt/iceberg/warehouse
      securityContext:
        capabilities:
          drop:
            - MKNOD
  serviceAccountName: containerroot
  volumes:
    - name: pgr24jamesvol1claim
      persistentVolumeClaim:
        claimName: pgr24jamesvol1claim
    - name: {{ .Values.pvc.iceberg.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.iceberg.name }}
    - name: hive-site-config-{{ .Values.instanceName }}
      configMap:
        name: hive-site-config-{{ .Values.instanceName }}
    - name: empty-warehouse
      emptyDir: {}
    - name: kube-api-access
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
