apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-{{ .Values.instanceName }}
  namespace: pgr24james
spec:
  selector:
    app: hive-pod-{{ .Values.instanceName }}
  ports:
    - protocol: TCP
      port: 9083
      targetPort: 9083
