apiVersion: v1
kind: Pod
metadata:
  name: test-pod-{{ .Values.instanceName }}
  namespace: pgr24james
spec:
  serviceAccountName: containerroot
  imagePullSecrets:
    - name: containerroot-dockercfg-qrptl
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  securityContext:
    seLinuxOptions:
      level: 's0:c29,c14'
    runAsUser: 0
  initContainers:
    - name: prefill
      image: macavaney/idabox:py310-v105
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          python /mnt/primary/Mini-project/Apache/System/Queries/TPCDS/Time_Workload/isolated_data/move_datalake.py --path {{ $.Values.pvc.iceberg.path }}
      volumeMounts:
        - name: pgr24jamesvol1claim
          mountPath: /mnt/primary
        - name: empty-warehouse
          mountPath: /mnt/empty_warehouse_dir
        - name: {{ $.Values.pvc.iceberg.name }}
          mountPath: {{ $.Values.pvc.iceberg.path }}
      resources:
        requests:
          cpu: "2"
          memory: "16Gi"
          ephemeral-storage: "300Gi"
        limits:
          cpu: "2"
          memory: "16Gi"
          ephemeral-storage: "300Gi"
      securityContext:
        capabilities:
          drop: [ "MKNOD" ]
  containers:
    - name: app-container
      image: {{ .Values.test.pod.image }}
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: pgr24jamesvol1claim
          mountPath: /mnt/primary
        - name: empty-warehouse
          mountPath: {{ $.Values.pvc.iceberg.path }}/warehouse/{{ $.Values.pvc.iceberg.db }}
      securityContext:
        capabilities:
          drop:
            - MKNOD
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "300Gi"
          limits:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "300Gi"
  serviceAccount: containerroot
  volumes:
    - name: pgr24jamesvol1claim
      persistentVolumeClaim:
        claimName: pgr24jamesvol1claim
    - name: {{ $.Values.pvc.iceberg.name }}
      persistentVolumeClaim:
        claimName: {{ $.Values.pvc.iceberg.name }}
    - name: empty-warehouse
      emptyDir: {}
    - name: kube-api-access-kkwjn
      projected:
        sources:
            - serviceAccountToken:
                expirationSeconds: 360700
                path: token
            - configMap:
                name: kube-root-ca.crt
                items:
                  - key: ca.crt
                    path: ca.crt
            - downwardAPI:
                items:
                  - path: namespace
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
            - configMap:
                name: openshift-service-ca.crt
                items:
                  - key: service-ca.crt
                    path: service-ca.crt
        defaultMode: 420