apiVersion: v1
kind: Service
metadata:
  name: trino-service-{{ .Values.instanceName }}
  namespace: pgr24james
  labels:
    service-app: trino-{{ .Values.instanceName }}
spec:
  selector:
    pod: trino-pod-{{ .Values.instanceName }}
  ports:
    - name: trino-coord
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
