{{- range $index, $nodeName := $.Values.trino.worker.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker-{{ $.Values.instanceName }}-{{ $index }}
  namespace: pgr24james
spec:
  serviceName: trino-worker-headless-{{ $.Values.instanceName }}  # Headless service for pod discovery
  replicas: {{ $.Values.trino.worker.replicasPerNode }}  # Adjust as needed
  selector:
    matchLabels:
      statefulsetSelector: trino-worker-{{ $.Values.instanceName }}-{{ $index }}
  template:
    metadata:
      labels:
        app: trino-worker-{{ $.Values.instanceName }}
        statefulsetSelector: trino-worker-{{ $.Values.instanceName }}-{{ $index }}
    spec:
      nodeName: {{ $nodeName }}
      serviceAccountName: containerroot
      imagePullSecrets:
        - name: containerroot-dockercfg-qrptl
      priority: 0
      schedulerName: default-scheduler
      enableServiceLinks: true
      terminationGracePeriodSeconds: 30
      preemptionPolicy: PreemptLowerPriority
      securityContext:
        seLinuxOptions:
          level: 's0:c29,c14'
        runAsUser: 0

      initContainers:
        - name: prefill
          image: macavaney/idabox:py310-v105
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              python /mnt/primary/Mini-project/Apache/System/Queries/TPCDS/Time_Workload/isolated_data/move_datalake.py --source_dir {{ $.Values.pvc.iceberg.path }}
          volumeMounts:
            - name: pgr24jamesvol1claim
              mountPath: /mnt/primary
            - name: empty-warehouse
              mountPath: /mnt/empty_warehouse_dir
            - name: {{ $.Values.pvc.iceberg.name }}
              mountPath: {{ $.Values.pvc.iceberg.path }}
          resources:
            requests:
              cpu: {{ $.Values.trino.worker.resources.cpu }}
              memory: {{ $.Values.trino.worker.resources.memory }}
            limits:
              cpu: {{ $.Values.trino.worker.resources.cpu }}
              memory: {{ $.Values.trino.worker.resources.memory }}
          securityContext:
            capabilities:
              drop: [ "MKNOD" ]

      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:v1.8.1
          args:
            - --path.procfs=/proc
            - --path.sysfs=/sys
            - --path.rootfs=/host
            - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
          ports:
            - containerPort: 9100
          securityContext:
            runAsUser: 0
        - name: trino-worker
          image: {{ $.Values.trino.pod.image }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - /bin/sh
            - -c
            - |
              echo "node.internal-address=${POD_IP}" >> /ect/trino/node.properties
              exec /lib/trino/bin/run-trino &
              /mnt/primary/Mini-project/Apache/System/Probe/trino_probe.sh "{{ $.Values.instanceName }}" "$POD_NAME"
          ports:
            - containerPort: 7071
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9189
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9101
              protocol: TCP
            - containerPort: 9102
              protocol: TCP
            - containerPort: 9103
              protocol: TCP
            - containerPort: 9104
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - MKNOD
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ $.Values.trino.worker.resources.cpu }}
              memory: {{ $.Values.trino.worker.resources.memory }}
            limits:
              cpu: {{ $.Values.trino.worker.resources.cpu }}
              memory: {{ $.Values.trino.worker.resources.memory }}
          volumeMounts:
            - name: pgr24jamesvol1claim
              mountPath: /mnt/primary
            - name: empty-warehouse
              mountPath: {{ $.Values.pvc.iceberg.path }}
            - name: trino-iceberg-config-{{ $.Values.instanceName }}
              mountPath: /etc/trino/catalog/iceberg.properties
              subPath: iceberg.properties
            - name: trino-worker-config-{{ $.Values.instanceName }}
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-jvm-config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-jmx-config
              mountPath: /etc/jmx-exporter-config.yml
              subPath: jmx-exporter-config.yml
          livenessProbe:
            httpGet: { path: /v1/info, port: 8080 }
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 2
      volumes:
        - name: pgr24jamesvol1claim
          persistentVolumeClaim:
            claimName: pgr24jamesvol1claim
        - name: {{ $.Values.pvc.iceberg.name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.pvc.iceberg.name }}
        - name: trino-iceberg-config-{{ $.Values.instanceName }}
          configMap:
            name: trino-iceberg-config-{{ $.Values.instanceName }}
        - name: trino-worker-config-{{ $.Values.instanceName }}
          configMap:
            name: trino-worker-config-{{ $.Values.instanceName }}
        - name: trino-jvm-config
          configMap:
            name: trino-jvm-config
        - name: trino-jmx-config
          configMap:
            name: trino-jmx-config
        - name: empty-warehouse
          emptyDir: {}
        - name: kube-api-access-kkwjn
          projected:
            sources:
              - serviceAccountToken:
                  expirationSeconds: 360700
                  path: token
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: ca.crt
              - downwardAPI:
                  items:
                    - path: namespace
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
              - configMap:
                  name: openshift-service-ca.crt
                  items:
                    - key: service-ca.crt
                      path: service-ca.crt
            defaultMode: 420
---
{{- end }}