apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coord-config-{{ .Values.instanceName }}
  namespace: pgr24james
data:
  config.properties: |
    http-server.process-forwarded=true
    #single node install config
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    node.environment=test
    query.max-memory-per-node:25GB
    memory.heap-headroom-per-node:5GB
    web-ui.authentication.type=FIXED
    web-ui.user=admin
    query.remote-task.max-error-duration=5m
    exchange.max-buffer-size=128MB
