apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coord-config-{{ .Values.instanceName }}
  namespace: pgr24james
data:
  config.properties: |
    http-server.process-forwarded=true
    #single node install config
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    node.environment=test
    memory.heap-headroom-per-node:5GB
    web-ui.authentication.type=FIXED
    web-ui.user=admin
    query.remote-task.max-error-duration=5m
    exchange.max-buffer-size=128MB
    query.max-stage-count=300
    query.max-memory-per-node:25GB
    query.max-memory-per-node:50GB
    query.max-memory=100GB
    spiller-spill-path=/mnt/iceberg/spill
    spill-enabled=true
    task.max-worker-threads=16
    exchange.http-client.request-timeout=10m
    exchange.http-client.idle-timeout=10m